tests:
  - test:
     name: install ceph pre-requisites
     module: install_prereq.py
     abort-on-fail: true

   - test:
      name: ceph ansible
      polarion-id: CEPH-83571467
      module: test_ansible.py
      config:
        is_mixed_lvm_configs: True
        ansi_config:
            ceph_test: True
            ceph_origin: distro
            ceph_stable_release: nautilus
            ceph_repository: rhcs
            osd_scenario: lvm
            journal_size: 1024
            ceph_stable: True
            ceph_stable_rh_storage: True
            fetch_directory: ~/fetch
            copy_admin_key: true
            dashboard_enabled: True
            dashboard_admin_user: admin
            dashboard_admin_password: p@ssw0rd
            grafana_admin_user: admin
            grafana_admin_password: p@ssw0rd
            node_exporter_container_image: registry.redhat.io/openshift4/ose-prometheus-node-exporter:v4.6
            grafana_container_image: registry.redhat.io/rhceph/rhceph-4-dashboard-rhel8:4
            prometheus_container_image: registry.redhat.io/openshift4/ose-prometheus:v4.6
            alertmanager_container_image: registry.redhat.io/openshift4/ose-prometheus-alertmanager:v4.6
            ceph_conf_overrides:
                global:
                  osd_pool_default_pg_num: 64
                  osd_default_pool_size: 2
                  osd_pool_default_pgp_num: 64
                  mon_max_pg_per_osd: 1024
                mon:
                  mon_allow_pool_delete: true
                client:
                  rgw crypt require ssl: false
                  rgw crypt s3 kms encryption keys: testkey-1=YmluCmJvb3N0CmJvb3N0LWJ1aWxkCmNlcGguY29uZgo=
                    testkey-2=aWIKTWFrZWZpbGUKbWFuCm91dApzcmMKVGVzdGluZwo=
            cephfs_pools:
              - name: "cephfs_data"
                pgs: "8"
              - name: "cephfs_metadata"
                pgs: "8"
      desc: osd with 6 osd scenarios with lvm
      destroy-cluster: False
      abort-on-fail: true

   - test:
      name: ceph ansible_idempotent_site.yaml
      polarion-id: CEPH-83573525
      module: test_ansible.py
      config:
        is_mixed_lvm_configs: True
        ansi_config:
            ceph_test: True
            ceph_origin: distro
            ceph_stable_release: nautilus
            ceph_repository: rhcs
            osd_scenario: lvm
            journal_size: 1024
            ceph_stable: True
            ceph_stable_rh_storage: True
            fetch_directory: ~/fetch
            copy_admin_key: true
            dashboard_enabled: True
            dashboard_admin_user: admin
            dashboard_admin_password: p@ssw0rd
            grafana_admin_user: admin
            grafana_admin_password: p@ssw0rd
            node_exporter_container_image: registry.redhat.io/openshift4/ose-prometheus-node-exporter:v4.6
            grafana_container_image: registry.redhat.io/rhceph/rhceph-4-dashboard-rhel8:4
            prometheus_container_image: registry.redhat.io/openshift4/ose-prometheus:v4.6
            alertmanager_container_image: registry.redhat.io/openshift4/ose-prometheus-alertmanager:v4.6
            ceph_conf_overrides:
                global:
                  osd_pool_default_pg_num: 64
                  osd_default_pool_size: 2
                  osd_pool_default_pgp_num: 64
                  mon_max_pg_per_osd: 1024
                mon:
                  mon_allow_pool_delete: true
                client:
                  rgw crypt require ssl: false
                  rgw crypt s3 kms encryption keys: testkey-1=YmluCmJvb3N0CmJvb3N0LWJ1aWxkCmNlcGguY29uZgo=
                    testkey-2=aWIKTWFrZWZpbGUKbWFuCm91dApzcmMKVGVzdGluZwo=
            cephfs_pools:
              - name: "cephfs_data"
                pgs: "8"
              - name: "cephfs_metadata"
                pgs: "8"
      desc: osd with 6 osd scenarios with lvm
      destroy-cluster: False
      abort-on-fail: true

   - test:
      name: config roll over new osd daemon
      polarion-id: CEPH-9583
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node9.*
                  daemon:
                      - osd
      desc: add new osd node with lvm scenario

   - test:
      name: config roll over existing osd daemon
      polarion-id: CEPH-9582
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          device: /dev/vdc
          add:
              - node:
                  node-name: .*node9.*
                  daemon:
                      - osd
      desc: add osd to existing node with lvm scenario

   - test:
      name: config roll over client daemon
      polarion-id: CEPH-83573550
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node9.*
                  daemon:
                      - client
      desc: add client daemon

   - test:
      name: config roll over rgw daemon
      polarion-id: CEPH-9581
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node3.*
                  daemon:
                      - rgw
      desc: add rgw

   - test:
      name: config roll over mds daemon
      polarion-id: CEPH-9581
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node4.*
                  daemon:
                      - mds
      desc: add mds

   - test:
      name: config roll over nfs daemon
      polarion-id: CEPH-9581
      module: test_ansible_roll_over.py
      config:
          is_mixed_lvm_configs: True
          add:
              - node:
                  node-name: .*node5.*
                  daemon:
                      - nfs
      desc: add nfs

   - test:
      name: shrink mon
      polarion-id: CEPH-9584
      module: shrink_mon.py
      config:
           mon-to-kill:
            - .*node6.*
      desc: remove monitor


   - test:
      name: shrink osd
      polarion-id: CEPH-9585
      module: shrink_osd.py
      config:
          osd-to-kill:
            - 2
      desc: shrink osd

   - test:
      name: Purge ceph dashboard
      polarion-id: CEPH-83573277
      module: purge_dashboard.py
      desc: Purges ceph dashboard

